"""Regenerate embedded RenoDX scene shaders and the final HDR converter."""
from pathlib import Path
import subprocess

repo = Path(__file__).resolve().parents[1]
root = repo / 'OptiScaler/shaders/hdr'
fxc = repo / 'OptiScaler/shaders/shader_tools/fxc.exe'

def compile_shader(source, profile, entry, output):
    subprocess.run([str(fxc), '/nologo', '/T', profile, '/E', entry,
                    '/O3', str(source), '/Fo', str(output)], check=True)
    return output.read_bytes()

def array(symbol, data):
    return ('inline constexpr unsigned char ' + symbol + '[] = {\n' +
            ''.join('    ' + ', '.join(f'0x{x:02x}' for x in data[i:i+16]) + ',\n'
                    for i in range(0, len(data), 16)) + '};\n')

header = '#pragma once\n// Generated by tests/compile_scene_hdr.py; MIT RenoDX shader adaptation.\n'
for name in ['Tonemap_0x85E777EF', 'PostTonemapPreLUT_0xF8F57F0A',
             'LUT_0x27EBC404', 'LUT_0x1F264D17', 'FullscreenGammaCorrection_0xF6E81A1B']:
    header += array(name, compile_shader(root / 'renodx' / (name + '.ps_5_0.hlsl'),
                                        'ps_5_0', 'main', root / 'renodx' / (name + '.cso')))
(root / 'renodx/SceneShaders.h').write_text(header, encoding='utf-8')
data = compile_shader(root / 'Hdr10.hlsl', 'cs_5_0', 'CSMain', root / 'Hdr10.cso')
(root / 'Hdr10_Shader.h').write_text('#pragma once\n' + array('Hdr10_cso', data), encoding='utf-8')

data = compile_shader(root / "DlssSceneInput.hlsl", "cs_5_0", "CSMain", root / "DlssSceneInput.cso")
(root / "DlssSceneInput_Shader.h").write_text("#pragma once\n" + array("DlssSceneInput_cso", data), encoding="utf-8")

data = compile_shader(root / "NrSceneInput.hlsl", "cs_5_0", "CSMain", root / "NrSceneInput.cso")
(root / "NrSceneInput_Shader.h").write_text("#pragma once\n" + array("NrSceneInput_cso", data), encoding="utf-8")
